// <auto-generated />
using Homework.NET_LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework.NET_LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251027100301_AddMoreClassicalAuthors")]
    partial class AddMoreClassicalAuthors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Homework.NET_LibraryAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = 1828,
                            Name = "Лев Толстой"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = 1799,
                            Name = "Александр Пушкин"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = 1952,
                            Name = "Роберт С. Мартин (Дядюшка Боб)"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = 1903,
                            Name = "Джордж Оруэлл"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = 1821,
                            Name = "Федор Достоевский"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = 1859,
                            Name = "Артур Конан Дойль"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = 1876,
                            Name = "Джек Лондон"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = 1939,
                            Name = "Маргарет Этвуд"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = -750,
                            Name = "Гомер"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = -428,
                            Name = "Платон"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = 1596,
                            Name = "Рене Декарт"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = 1724,
                            Name = "Иммануил Кант"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = 354,
                            Name = "Блаженный Августин"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = 329,
                            Name = "Василий Великий"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = 1056,
                            Name = "Нестор Летописец"
                        });
                });

            modelBuilder.Entity("Homework.NET_LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 1869,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublishedYear = 1877,
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            PublishedYear = 1833,
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            PublishedYear = 2008,
                            Title = "Чистый код"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            PublishedYear = 1945,
                            Title = "Скотный двор"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            PublishedYear = 1866,
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            PublishedYear = 1868,
                            Title = "Идиот"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            PublishedYear = 1887,
                            Title = "Этюд в багровых тонах"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            PublishedYear = 1902,
                            Title = "Собака Баскервилей"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            PublishedYear = 1909,
                            Title = "Мартин Иден"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 7,
                            PublishedYear = 1906,
                            Title = "Белый Клык"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            PublishedYear = 1985,
                            Title = "Рассказ служанки"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 9,
                            PublishedYear = -750,
                            Title = "Илиада"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 9,
                            PublishedYear = -750,
                            Title = "Одиссея"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 10,
                            PublishedYear = -380,
                            Title = "Государство"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 11,
                            PublishedYear = 1637,
                            Title = "Дискорс о методе"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 12,
                            PublishedYear = 1781,
                            Title = "Критика чистого разума"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 13,
                            PublishedYear = 397,
                            Title = "Исповедь"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 13,
                            PublishedYear = 426,
                            Title = "О граде Божием"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 14,
                            PublishedYear = 370,
                            Title = "Шестоднев"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 15,
                            PublishedYear = 1113,
                            Title = "Повесть временных лет"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 15,
                            PublishedYear = 1037,
                            Title = "Слово о законе и благодати"
                        });
                });

            modelBuilder.Entity("Homework.NET_LibraryAPI.Models.Book", b =>
                {
                    b.HasOne("Homework.NET_LibraryAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Homework.NET_LibraryAPI.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
